[package]
name = "adafruit"
version = "0.1.0"
authors = ["Gabriel Feron <feron.gabriel@gmail.com>"]
edition = "2018"

[dependencies]
rppal = { git = "https://github.com/golemparts/rppal" }
bmp = "*"

[patch.crates-io]
rppal = { git = "https://github.com/gferon/rppal", branch="musl-fixes" }